config/routes.rb
Rails.application.routes.draw do
  devise_for :users

  scope '(:locale)', locale: /#{I18n.available_locales.join('|')}/ do
    resources :pages do
      resources :sections, except: %i[index show]
      member do
        get :history
      end
    end

    resources :users, only: %i[index show]
    root 'main#index'
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    user ||= User.new # guest user (not logged in)
    can :manage, [Page, Section]

    if user.role? :admin
      can :manage, :all
    else
      can :read, :all
    end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/block.rb
class Block < ApplicationRecord
  belongs_to :page

  translates :name, :content

  globalize_accessors locales: I18n.available_locales,
                   attributes: [:name, :content]
  accepts_nested_attributes_for :translations

  validates :name, :content, presence: true

end

app/models/page.rb
class Page < ApplicationRecord
  has_many :sections

  translates :name, :locale,
    versioning: { :gem => :paper_trail, options: { on: [ :update ], ignore: [:updated_at] } }

  globalize_accessors locales: I18n.available_locales,
                   attributes: [:name]
  accepts_nested_attributes_for :translations

  validates :name, presence: true

  def to_param
    if name?
      "#{id}-#{name.parameterize}"
    else
      id
    end
  end
end

app/models/section.rb
class Section < ApplicationRecord
  belongs_to :page

  translates :name, :content

  globalize_accessors locales: I18n.available_locales,
                   attributes: [:name, :content]
  accepts_nested_attributes_for :translations

  validates :name, :content, presence: true
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable, :lockable

  ROLES = %w[guest user]

  def roles=(roles)
    self.roles_mask = (roles & ROLES).map { |r| 2**ROLES.index(r) }.sum
  end

  def roles
    ROLES.reject { |r| ((roles_mask || 0) & 2**ROLES.index(r)).zero? }
  end

  def self.with_role(role)
    where('roles_mask & ? > 0', 2**ROLES.index(role.to_s))
  end

  def role?(role)
    roles.include? role.to_s
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :set_paper_trail_whodunnit
  around_action :set_locale

  def set_locale(&action)
    # lang = current_user ? current_user.profile.language : extract_locale_from_accept_language_header
    lang = extract_locale_from_accept_language_header
    locale = params[:locale] || lang
    I18n.with_locale(locale, &action)
  end

  def default_url_options
    { locale: I18n.locale }
  end

  def user_for_paper_trail
    current_user ? current_user.email : 'undefined user'  # or whatever
  end

  private

    def extract_locale_from_accept_language_header
      default_lang = :en
      lang_request = request.env['HTTP_ACCEPT_LANGUAGE']

      if lang_request.nil?
        default_lang
      else
        locale = lang_request.scan(/^[a-z]{2}/).first.to_sym
        (I18n.available_locales.include? locale) ? locale : default_lang
      end
    end
end

app/controllers/main_controller.rb
class MainController < ApplicationController
  def index
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  load_and_authorize_resource

  def index
    @pages = @pages.with_translations(I18n.locale)
  end

  def show
    @sections = @page.sections.with_translations(I18n.locale)
  end

  def history
    @versions = @page.translation_for(I18n.locale).versions.reverse
  end

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @page.save
        format.html { redirect_to @page, notice: 'Page was successfully created.' }
        format.json { render :show, status: :created, location: @page }
      else
        format.html { render :new }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @page.update(page_params)
        format.html { redirect_to @page, notice: 'Page was successfully updated.' }
        format.json { render :show, status: :ok, location: @page }
      else
        format.html { render :edit }
        format.json { render json: @page.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @page.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Page was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def page_params
#  params.fetch(:page, { translations_attributes: %i[id locale name] })
      params.require(:page).permit(
        { translations_attributes: %i[id locale name] }
      )

    end
end

app/controllers/sections_controller.rb
class SectionsController < ApplicationController
  load_and_authorize_resource :page
  load_and_authorize_resource :section, through: :page

  def new
  end

  def edit
  end

  def create
    respond_to do |format|
      if @section.save
        format.html { redirect_to @page, notice: 'Section was successfully created.' }
        format.json { render :show, status: :created, location: @section }
      else
        format.html { render :new }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @section.update(section_params)
        format.html { redirect_to @page, notice: 'Section was successfully updated.' }
        format.json { render :show, status: :ok, location: @section }
      else
        format.html { render :edit }
        format.json { render json: @section.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @section.destroy
    respond_to do |format|
      format.html { redirect_to @page, notice: 'Section was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    def section_params
      params.require(:section).permit(
        :page_id,
        :position,
        { translations_attributes: %i[id locale name content] }
      )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource

  def index
    @users = @users.order(:email)
  end

  def show
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def plural(count, value, locale = I18n.locale)
    # custom pluralization
    if ['ru', :ru].include? locale
      # for russian pluralization
      val = "plural.#{value}"
      text = Russian.p(count, t("#{val}_1", locale: locale), t("#{val}_2", locale: locale), t("#{val}_10", locale: locale))
    else
      text = value.pluralize(count)
    end
    [count, text].join(' ')
  end
end

app/views/blocks/new.html.haml
%h1 New block

= render 'form'

= link_to 'Back', @page

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title Wikionrails
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_include_tag 'application', 'data-turbolinks-track': 'reload'
  %body
    .container-fluid
      .row
        .col-sm-4.col-md-3.col-lg-2.border-right
          = link_to root_path do
            = image_tag 'logo.png', class: 'img-fluid mt-3'

          .mt-3
            .text-muted.border-bottom.mb-1= t 'main.other_langs'
            %ul.list-unstyled
              - I18n.available_locales.each do |locale|
                %li= link_to t("locales.#{locale}"), url_for(locale: locale)

        .col
          .row
            .col-12
              = render 'users/userbar'
            .col-12
              = yield

app/views/main/index.html.haml
.row
  .col-12
    .bg-light.border.p-5
      .row
        .col
          .lead
            = t 'main.welcome_first_html', url: link_to(t('main.to_wiki'), root_path)
            %br/
            = t 'main.welcome_second'
        .col.text-right
          .mb-3= t 'main.articles_count_now_html', count: link_to(plural(Page.with_translations(I18n.locale).count, 'page'), pages_path)
          = link_to t('pages.new'), new_page_path, class: 'btn btn-secondary'

app/views/pages/_form.html.haml
= bootstrap_form_for @page do |f|
  - if @page.errors.any?
    #error_explanation
      %h2= "#{pluralize(@page.errors.count, "error")} prohibited this page from being saved:"
      %ul
        - @page.errors.full_messages.each do |message|
          %li= message

  = f.globalize_fields_for locale do |g|
    .form-group
      = g.label :name, Page.human_attribute_name(:name)
      ~ g.text_field :name, class: 'form-control'

  .actions
    = f.submit t('actions.save')

app/views/pages/_version.html.haml
.card.mb-4
  .card-body
    .text-muted= l(version.created_at, format: "%-d.%m.%Y %H:%M:%S")
    = link_to version.actor, version.actor if version.actor

    - if version.event == 'update'
      %ul.list-group.list-group-flush.list-group-sm
        - version.changeset.each do |changeitem|
          %li.list-group-item.p-1
            .row
              .col
                %strong= Page.human_attribute_name(changeitem[0])
              .col= changeitem[1][0] ? content_tag(:span, t('shared.empty'), class: 'text-muted') : changeitem[1][0]
              .col
                = changeitem[1][1]

app/views/pages/edit.html.haml
%h2 Editing page

= render 'form'

= link_to 'Show', @page

app/views/pages/history.html.haml
- set_meta_tags title: t('shared.history')

%h1.h3.border-bottom= link_to @page.name, @page

.row
  .col
    - if @versions.empty?
      .text-center.my-5
        .h3.text-muted= t('history.empty')
    - else
      = render(partial: 'version', collection: @versions)

app/views/pages/index.html.haml
.row
  .col
    %h1= t('pages.listing')
  .col.text-right
    = link_to 'New Page', new_page_path, class: 'btn btn-sm btn-secondary'

.row
  .col
    %ul
      - @pages.each do |page|
        %li
          = link_to page.name, page

app/views/pages/new.html.haml
%h2 New page

= render 'form'

app/views/pages/show.html.haml
- if @page.translation_for(locale).id?

  %h1.h3.border-bottom= @page.name

  .mb-3.text-right
    %small
      = link_to t('main.history'), history_page_path(@page)
      \|
      = link_to t('actions.edit'), edit_page_path(@page)
      \|
      = link_to t('actions.destroy'), @page, method: :delete, data: { confirm: 'Are you sure?' }

  .row
    .col.text-center
      .p-2.bg-light.mb-3
        = link_to t('sections.new'), new_page_section_path(@page)

  = render @sections

- else
  .text-center.my-5
    .h3.text-muted= t('history.empty')
    You can #{link_to 'create page', edit_page_path(@page)} on this locale

app/views/sections/_form.html.haml
= bootstrap_form_for [@page, @section] do |f|
  - if @section.errors.any?
    #error_explanation
      %h2= "#{pluralize(@section.errors.count, "error")} prohibited this section from being saved:"
      %ul
        - @section.errors.full_messages.each do |message|
          %li= message

  = f.globalize_fields_for locale do |g|
    .form-group
      = g.label :name, Section.human_attribute_name(:name)
      ~ g.text_field :name, class: 'form-control'

    .form-group
      = g.label :content, Section.human_attribute_name(:content)
      ~ g.text_area :content, class: 'form-control'

  = f.submit 'Save'

app/views/sections/_section.html.haml
.row
  .col-12
    .border-bottom
      .h6.float-left
        = section.name
      %small.float-right
        = link_to t('actions.edit'), edit_page_section_path(@page, section)
        \|
        = link_to t('actions.destroy'), [@page, section], method: :delete, data: { confirm: 'Are you sure?' }

      .clearfix
  .col-12
    = section.content

app/views/sections/edit.html.haml
%h1 Editing section

= render 'form'

= link_to 'Back', @page

app/views/sections/new.html.haml
%h1 New section

= render 'form'

= link_to 'Back', @page

app/views/users/_userbar.html.haml
%ul.list-inline.text-right.my-2
  %li.list-inline-item
    = fa_icon 'user'
  - if user_signed_in?
    %li.list-inline-item= link_to current_user.email, current_user
    %li.list-inline-item= link_to t('users.logout'), destroy_user_session_path, method: :delete
  - else
    %li.list-inline-item= link_to t('users.signup'), new_user_registration_path
    %li.list-inline-item= link_to t('users.login'),  new_user_session_path

app/views/users/index.html.haml
%ul
  - @users.each do |user|
    %li= user.email

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/users/show.html.haml
%h1.h3= @user.email